services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: titan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./titan.sql:/docker-entrypoint-initdb.d/1-titan.sql
      - ./inserts.sql:/docker-entrypoint-initdb.d/2-inserts.sql

volumes:
  mysql_data: